# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest


variables:
  imageName: 'poc'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo "Installing mlocate and updating the database"
    sudo apt-get update
    sudo apt-get install -y mlocate
    sudo updatedb
    echo "Locating the file"
    locate poc.jar
    displayName: 'Locate File'

   

- script: pwd
  displayName: 'Print your current folder'

- script: |
    echo "Printing directory tree"
    sudo apt-get update && sudo apt-get install -y tree
    tree $(Build.ArtifactStagingDirectory)/drop
    displayName: 'Print Directory Tree'

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: devops/Dockerfile
    buildContext: '$(Agent.BuildDirectory)'

