apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
  labels:
    app: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - name: poc
        image: my-app:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: dbUrl
          value: jdbc:mysql://mysql-service/testdb
        - name: userName 
          value: root
        - name: password 
          value: root
        - name: driverClass 
          value: com.mysql.jdbc.Driver
---
apiVersion: v1
kind: Service
metadata:
  name: poc-service
spec:
  selector:
    app: poc
  type: LoadBalancer
 # externalIPs:
 # - 192.168.49.2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    
      nodePort: 30000
       
